[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tza-pypsa"
version = "0.0.1"
description = "PyPSA models created by the Analysis team at TransitionZero"
authors = [
    { name = "Aman Majid", email = "aman.m@transitionzero.org" }
]
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "pypsa",
    "pandas",
    "cartopy",
    "plotly",
    "requests",
    "h5netcdf",
]

[tool.setuptools]
packages = ["tz_pypsa", "stock_models"]  # List both packages explicitly

[tool.setuptools.package-data]
"stock_models" = ["**/*.yaml"]  # YAML files should be under stock_models package