# -------------------------------------------------------------------------
#
#   CONFIGS
#   
#     Define the model configurations
#
#     Link to docs: 
#       N/A
#
#     Authors:
#       - @amanmajid
#
# -------------------------------------------------------------------------

# -------
# File paths
# -------

file_paths:
  timeseries: 'data/clean/ASEAN/timeseries_2023.nc'

# -------
# Time definitions
# -------

time_definition:
  id: asean_default_temporal_resolution
  years: [2022, 2030, 2040, 2050]
  frequency: '24h'
  multi_year_discount_rate: 0.02

# -------
# Emissions targets
# -------

emissions_targets:
  CO2:
    2022: 9999999999
    2030: 9999999999
    2040: 9999999999
    2050: 9999999999