# -------------------------------------------------------------------------
#
#   CONFIGS
#   
#     Define the model configurations
#
#     Link to docs: 
#       N/A
#
#     Authors:
#       - @amanmajid
#
# -------------------------------------------------------------------------

# -------
# File paths
# -------

file_paths:
  annual_demand: '../data/raw/ASEAN/specified_annual_demand.csv'
  demand_profile: '../data/raw/ASEAN/specified_demand_profile.csv'

# -------
# Time definitions
# -------

time_definition:
  id: asean_default_temporal_resolution
  year: 2022
  resolution: 'h'
  multi_year_investment: false

# -------
# Emissions targets
# -------

impacts:
  - id: CO2
    long_name: equivalent carbon dioxide emissions
    description: equivalent carbon dioxide emissions
    exogenous_annual: 0.
    exogenous_total: null
    constraint_annual: null
    constraint_total: null
  - id: NOx
    long_name: equivalent carbon dioxide emissions
    description: equivalent carbon dioxide emissions
    exogenous_annual: 0.
    exogenous_total: null
    constraint_annual: null
    constraint_total: null
  - id: SOx
    long_name: equivalent carbon dioxide emissions
    description: equivalent carbon dioxide emissions
    exogenous_annual: 0.
    exogenous_total: null
    constraint_annual: null
    constraint_total: null