MOEA:
  number_of_objectives: 2
  number_of_constraints: 1
  number_of_cores: 16
  number_of_generations: 10000
  number_of_seeds: 16
  infeasible_objective_penalty: 1e999
  infeasible_cfe_penalty: -99

ASEAN:
  countries: ['SGP']
  local_bus: 'SGP'
  cfe_score: 50
  fossil_generators: ['coal', 'gas']
  p_nom_max: 1e5